### ISSUE TITLE
reduce slides

### ISSUE THREAD

**Issue by brry** [brry/loopfun#1]
- Reduce all slides we won't show anyways
- Reduce exercises to coherent set

**Comment by jnnsbrr** [comment]
Since I don`t know what your plans are for the future and we are working on the master I just commented out the non relevant sections. If you have the material somewhere else anyway we can also delete it but thats up to you. 
We should maybe also speak in detail about the slides - maybe on monday somewhen between 8:00 and 15:00?
So then we add some adjustments and I can commit it to SWC repo (has to be done until the 20th, next Wednesday)
Thanks!
